### ISSUE TITLE
How do I setup stacker_profiles for multiple target accounts?

### ISSUE THREAD

**Issue by thomasdpage** [thedojoseries/codepipeline#1]
Hi,

Just stumbled upon this really great resource.  Every example I've found of using Stacker is good - but I can't get my head round how I setup stacker profiles for more than one target account?

Please can you help?

**Comment by thomasdpage** [comment]
I had a mismatch between my Stacker config and profiles.  Your video on Youtube explained things really well so thank you!

**Comment by thedojoseries** [comment]
Oh, I'm really glad you figured it out! :D @thomasdpage If you have any other questions regarding other videos/repos, don't hesitate to reach out just like you did!

**Comment by thomasdpage** [comment]
@thedojoseries I have another question.  How can I use Stacker to deploy to multiple accounts, but not all at the same time.  For example, I might want manual approval of CFN change sets in Dev before proceeding to Prod.  Stacker seems to be all or nothing.

I found a [blog post](https://aws.amazon.com/blogs/opensource/multi-environment-ci-cd-pipelines-with-aws-codepipeline-and-open-source-tools/) from AWS but it doesn't explain this very well.

**Comment by thedojoseries** [comment]
Ok, I see. So in that case, what you could do is to separate the profiles and execute two separate `stacker build` commands. 
In your AWS credentials file, you could have a profile for dev and one for prod:

```
[profile stacker_master_dev]
role_arn = [ROLE_ARN]
credential_source = EcsContainer
role_session_name = stacker_master_role_session_dev

[profile stacker_execution_dev]
role_arn = arn:aws:iam::[DEV_ACCOUNT_ID]:role/[StackerExecutorRoleName]
source_profile = stacker_master_dev

[profile stacker_master_prod]
role_arn = [ROLE_ARN]
credential_source = EcsContainer
role_session_name = stacker_master_role_session_prod

[profile stacker_execution_prod]
role_arn = arn:aws:iam::[PROD_ACCOUNT_ID]:role/[StackerExecutorRoleName]
source_profile = stacker_master_prod
```

Then in your pipeline, you can run `stacker build (...) --profile stacker_master_dev`, have an approval step, then later run `stacker build (...) --profile stacker_master_prod`.

There's another option which I haven't tested which is to run `stacker build` with `--interactive` so that you're asked to confirm before a stack is deployed. But this might not be what you want. Might be easier to separate the runs like I mentioned and rely on the pipeline to get confirmation before proceeding.

Hope this helps you somehow. I don't work daily with Stacker so there could be better ways of doing this with the latest versions, but I think this approach could be a good starting point.

**Comment by thomasdpage** [comment]
Great - thank you.  I'll look into that and hopefully get it working the way I want it to.
